embedding_size: 64
latent_embedding: 64

n_layers: 3
reg_weight: [1e-5]     # 0.00001, 0.0001, 0.001, 0.01, 0.1
learning_rate: [1e-4]        # 0.0001, 0.001, 0.01, 0.1, 1


hyper_parameters: ["reg_weight", "learning_rate"]