# Common Features
USER_ID_FIELD: userID
ITEM_ID_FIELD: itemID
# RATING_FIELD: rating
TIME_FIELD: timestamp

filter_out_cod_start_users: True

inter_file_name: 'clean_filtered_interactions_with_ts.csv'

# name of frozen features
vision_feature_file: 'clean_audio_feat_ts.npy'
text_feature_file: 'clean_text_feat_ts.npy'
user_graph_dict_file: 'user_graph_dict.npy'       # Run generate-u-u-matrix.py

field_separator: "\t"
