USER_ID_FIELD: userID
ITEM_ID_FIELD: itemID
TIME_FIELD: timestamp
filter_out_cod_start_users: true
inter_file_name: cs_lowcount_10/clean_lowcount_coldstart_interactions.csv
vision_feature_file: cs_lowcount_10/clean_audio_feat_mert.npy
text_feature_file: cs_lowcount_10/clean_text_feat.npy
user_graph_dict_file: user_graph_dict.npy
field_separator: "\t"
